### ISSUE TITLE
How to do, In platform/production updates

### ISSUE THREAD

**Issue by ridingmower** [axuno/Volleyball-League#139]
Hello this is great love the sports league.

When patches are released how can we do updates like wordpress on the site, without loosing custom work
How can we add new functionality,  I want support other sports do you have adapters?

**Comment by axunonb** [comment]
Hi, currently Volleyball-League only targets volleyball sports. Creating adapters for other sports would require quite an effort, I guess.
`League` is a Razor Class Library, that you can integrate with another project. Have a look at the demo project that is included in this repo. The demo references the `League` project. However, you can `pack` `League`, and then reference this package (like a NuGet package) in any other project. We do the same with our real life [Volleyball League](https://volleyball-liga.de/).
Of course, all changes and releases are published on GitHub. We considered publishing `League` on NuGet, but the community using it would be rather small - so we didn't.

**Comment by axunonb** [comment]
Hm, that's weird. I'm out of office till end of next week. Then I can take a look. Guess this is easy to fix.

> Also how hard is it to make it BS 5

Well, we are on Bootstrap v5.3.2 (if I interpret BS 5 correctly).

**Comment by axunonb** [comment]
> Net8

Yes, we skipped Net7 and will move to Net8, because of LTS

> Exception with `webBuilder.UseWebRoot("wwwroot")`

We could reproduce the exception after loading the repo from GitHub.
But it disappeared afterwards and wouldn't assign wwwroot from the League RCL correctly. Couldn't figure out how this can happen. But if it works with Net8 it's not worth the time to investigate further. In our production environment all works as it should though.

> `LeagueStartup`

`LeagueStartup` is the class that will initialize the components of the League Razor Class Library. And there is also a `WebStartup` class for customizing.

> LlblGenPro

We're using this tool for the DAL because it's really powerful. Unfortunately it's not free, except for the runtime packages. As long as you keep the database unchanged, there is no urgent need for it.

**Comment by axunonb** [comment]
> identity update in net8

Will have a look at these updates, hoping there are no breaking changes.

> made the error disappear

Actually it "just disappeared", and as you mentioned after migrating to net8 it does not throw I did not investigate further. In case I understood that wrong, I could have a deeper look.

> LlblGenPro

Fully understand your thoughts, and even without CRUD generated code this task is simple to implement.

> LeagueStartup

I chose the name because only the RCL get initialized here. In the live website there is another "Startup" which I call `WebStartup` to initialize the web app. There is no magic behind.

As seem to be interested in the library, what exactly do you have in mind with it?
